/**
 * db-ids: verify that case/visit IDs are generated by the store, not the DB,
 * and that scoped deletes prevent cross-household operations.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'

// ── Lightweight mocks ────────────────────────────────────────────────────────

const created: { cases: any[]; expected: any[]; recurring: any[] } = { cases: [], expected: [], recurring: [] }
const deleted: { expected: string[]; recurring: string[] } = { expected: [], recurring: [] }

vi.mock('@/lib/db/cases', () => ({
  createCase:            (d: any) => { created.cases.push(d); return Promise.resolve(d) },
  getCasesForHousehold:  () => Promise.resolve([]),
  updateCase:            () => Promise.resolve({}),
  deleteOldCases:        () => Promise.resolve({}),
  getCase:               () => Promise.resolve(null),
  getOpenCasesForHousehold: () => Promise.resolve([]),
}))

vi.mock('@/lib/db/visits', () => ({
  createExpectedVisit:       (d: any) => { created.expected.push(d); return Promise.resolve(d) },
  createRecurringVisit:      (d: any) => { created.recurring.push(d); return Promise.resolve(d) },
  getExpectedVisitsForHousehold:  () => Promise.resolve([]),
  getRecurringVisitsForHousehold: () => Promise.resolve([]),
  getActiveExpectedVisits:   () => Promise.resolve([]),
  deleteExpectedVisit:       (_hid: string, id: string) => { deleted.expected.push(id); return Promise.resolve({}) },
  deleteRecurringVisit:      (_hid: string, id: string) => { deleted.recurring.push(id); return Promise.resolve({}) },
  deleteOldExpectedVisits:   () => Promise.resolve({}),
  updateRecurringVisit:      () => Promise.resolve({}),
}))

vi.mock('@/lib/db/households', () => ({
  getHousehold:         (id: string) => Promise.resolve({ id, residentName: 'R', timezone: 'UTC', timeoutSec: 30, quietEnabled: false, quietStartHour: 22, quietEndHour: 6, emergencyNumber: '112', plannedMode: 'helper' }),
  updateHousehold:      () => Promise.resolve({}),
  getResidentEpoch:     () => Promise.resolve(1),
  getMembershipsForHousehold: () => Promise.resolve([]),
}))

vi.mock('@/lib/db/memberships', () => ({
  getApprovedMemberships: () => Promise.resolve([]),
  getMembership:          () => Promise.resolve(null),
}))

vi.mock('@/lib/db/client', () => ({
  getDb: () => ({ device: { findMany: () => Promise.resolve([]) } }),
}))

vi.mock('@/lib/ring/client', () => ({
  ringConfiguredForHousehold: () => Promise.resolve(false),
  getConnectionForHousehold:  () => Promise.resolve(null),
}))

// ── Tests ────────────────────────────────────────────────────────────────────

import { addExpected, removeExpected, addRecurring, removeRecurring } from '@/lib/doorbell/store'

describe('visit IDs are store-generated', () => {
  beforeEach(() => {
    created.expected.length  = 0
    created.recurring.length = 0
    deleted.expected.length  = 0
    deleted.recurring.length = 0
  })

  it('addExpected generates an id starting with "exp_"', async () => {
    const v = await addExpected('hh1', '👤', 'Test', Date.now(), Date.now() + 3600_000)
    expect(v.id).toMatch(/^exp_/)
    expect(created.expected.length).toBe(1)
    expect(created.expected[0].id).toBe(v.id)
  })

  it('addRecurring generates an id starting with "rec_"', async () => {
    const v = await addRecurring('hh1', { icon: '👤', label: 'Weekly', days: [1], everyNWeeks: 1, startMin: 600, endMin: 660, alertIfMissed: false, startNextWeek: false })
    expect(v.id).toMatch(/^rec_/)
    expect(created.recurring.length).toBe(1)
    expect(created.recurring[0].id).toBe(v.id)
  })

  it('removeExpected passes householdId to deleteExpectedVisit', async () => {
    const v = await addExpected('hh1', '👤', 'Test', Date.now(), Date.now() + 3600_000)
    await removeExpected('hh1', v.id)
    expect(deleted.expected).toContain(v.id)
  })

  it('removeRecurring passes householdId to deleteRecurringVisit', async () => {
    const v = await addRecurring('hh1', { icon: '👤', label: 'Weekly', days: [1], everyNWeeks: 1, startMin: 600, endMin: 660, alertIfMissed: false, startNextWeek: false })
    await removeRecurring('hh1', v.id)
    expect(deleted.recurring).toContain(v.id)
  })

  it('addExpected saves who and passphrase to DB', async () => {
    await addExpected('hh1', '🩺', 'Doctor', Date.now(), Date.now() + 3600_000, 'Dr. Sharma', 'sunshine')
    expect(created.expected[0].who).toBe('Dr. Sharma')
    expect(created.expected[0].passphrase).toBe('sunshine')
  })

  it('addRecurring saves who and passphrase to DB', async () => {
    await addRecurring('hh1', { icon: '🧹', label: 'Cleaner', days: [1], everyNWeeks: 1, startMin: 600, endMin: 660, alertIfMissed: false, startNextWeek: false, who: 'Maria', passphrase: 'mango' })
    expect(created.recurring[0].who).toBe('Maria')
    expect(created.recurring[0].passphrase).toBe('mango')
  })
})
